# Site settings
course_name: TigerAI - LSU/IBM AI security summer boot camp
course_description: "Designed for students and aspiring professionals, this five-day program offers a comprehensive curriculum covering Machine Learning fundamentals, Federated Learning, Large Language Models, and AI Data Security. Participants will benefit from expert-led lectures, engaging demos, and hands-on labs, complemented by opportunities to network with industry leaders and peers. Upon completion, attendees will receive a certificate recognized by LSU and IBM, marking their achievements in this cutting-edge field. Join us for this transformative learning experience and be part of shaping the future of technology."
course_semester: "Summer 2024"

baseurl: "/TigerAIWebsite/" # the subpath of your site, e.g. /blog/
url: "http://hudzum.github.io/" # the base hostname & protocol for your site

schoolname: "LSU"
schoolurl: "https://www.lsu.edu"
twitter_username: "tigeraibootcamp@gmail.com"

address: |
    Louisiana State University
    Baton Rouge
    Louisiana


# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
